[2022-06-06 11:55:06,320] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: hands_on_test.copy_order_detail_data manual__2022-06-06T11:48:14.551686+00:00 [queued]>
[2022-06-06 11:55:06,337] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: hands_on_test.copy_order_detail_data manual__2022-06-06T11:48:14.551686+00:00 [queued]>
[2022-06-06 11:55:06,338] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-06 11:55:06,339] {taskinstance.py:1357} INFO - Starting attempt 4 of 4
[2022-06-06 11:55:06,340] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-06 11:55:06,363] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): copy_order_detail_data> on 2022-06-06 11:48:14.551686+00:00
[2022-06-06 11:55:06,370] {standard_task_runner.py:52} INFO - Started process 672 to run task
[2022-06-06 11:55:06,376] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'hands_on_test', 'copy_order_detail_data', 'manual__2022-06-06T11:48:14.551686+00:00', '--job-id', '71', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp_w8ad6qs', '--error-file', '/tmp/tmpq2pfybmi']
[2022-06-06 11:55:06,378] {standard_task_runner.py:80} INFO - Job 71: Subtask copy_order_detail_data
[2022-06-06 11:55:06,464] {task_command.py:369} INFO - Running <TaskInstance: hands_on_test.copy_order_detail_data manual__2022-06-06T11:48:14.551686+00:00 [running]> on host 078df8b61ea1
[2022-06-06 11:55:06,583] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=pathairs
AIRFLOW_CTX_DAG_ID=hands_on_test
AIRFLOW_CTX_TASK_ID=copy_order_detail_data
AIRFLOW_CTX_EXECUTION_DATE=2022-06-06T11:48:14.551686+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-06T11:48:14.551686+00:00
[2022-06-06 11:55:06,598] {base.py:68} INFO - Using connection ID 'postgres_db' for task execution.
[2022-06-06 11:55:06,625] {dbapi.py:208} INFO - Running statement: 
COPY order_detail FROM '/var/lib/postgresql/data/order_detail.csv' DELIMITER ',' CSV HEADER;, parameters: None
[2022-06-06 11:55:06,632] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 92, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 188, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 212, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedFile: could not open file "/var/lib/postgresql/data/order_detail.csv" for reading: No such file or directory
HINT:  COPY FROM instructs the PostgreSQL server process to read a file. You may want a client-side facility such as psql's \copy.

[2022-06-06 11:55:06,645] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=hands_on_test, task_id=copy_order_detail_data, execution_date=20220606T114814, start_date=20220606T115506, end_date=20220606T115506
[2022-06-06 11:55:06,665] {standard_task_runner.py:97} ERROR - Failed to execute job 71 for task copy_order_detail_data (could not open file "/var/lib/postgresql/data/order_detail.csv" for reading: No such file or directory
HINT:  COPY FROM instructs the PostgreSQL server process to read a file. You may want a client-side facility such as psql's \copy.
; 672)
[2022-06-06 11:55:06,709] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-06 11:55:06,773] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
