[2022-06-07 09:24:51,166] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: hands_on_test.copy_restaurant_detail_data manual__2022-06-07T09:24:47.019520+00:00 [queued]>
[2022-06-07 09:24:51,189] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: hands_on_test.copy_restaurant_detail_data manual__2022-06-07T09:24:47.019520+00:00 [queued]>
[2022-06-07 09:24:51,191] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-07 09:24:51,192] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-06-07 09:24:51,193] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-07 09:24:51,228] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): copy_restaurant_detail_data> on 2022-06-07 09:24:47.019520+00:00
[2022-06-07 09:24:51,237] {standard_task_runner.py:52} INFO - Started process 18102 to run task
[2022-06-07 09:24:51,252] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'hands_on_test', 'copy_restaurant_detail_data', 'manual__2022-06-07T09:24:47.019520+00:00', '--job-id', '86', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpcdnaz_p3', '--error-file', '/tmp/tmpmrnmo56f']
[2022-06-07 09:24:51,255] {standard_task_runner.py:80} INFO - Job 86: Subtask copy_restaurant_detail_data
[2022-06-07 09:24:51,345] {task_command.py:369} INFO - Running <TaskInstance: hands_on_test.copy_restaurant_detail_data manual__2022-06-07T09:24:47.019520+00:00 [running]> on host a4a1e1d603db
[2022-06-07 09:24:51,476] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=pathairs
AIRFLOW_CTX_DAG_ID=hands_on_test
AIRFLOW_CTX_TASK_ID=copy_restaurant_detail_data
AIRFLOW_CTX_EXECUTION_DATE=2022-06-07T09:24:47.019520+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-07T09:24:47.019520+00:00
[2022-06-07 09:24:51,491] {base.py:68} INFO - Using connection ID 'postgres_db' for task execution.
[2022-06-07 09:24:51,504] {dbapi.py:208} INFO - Running statement: 
COPY restaurant_detail FROM '/var/lib/postgresql/data/lmwn/restaurant_detail.csv' DELIMITER ',' CSV HEADER;, parameters: None
[2022-06-07 09:24:51,521] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 92, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 188, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 212, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "restaurant_detail_pkey"
DETAIL:  Key (id)=(R_99988) already exists.
CONTEXT:  COPY restaurant_detail, line 2

[2022-06-07 09:24:51,536] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=hands_on_test, task_id=copy_restaurant_detail_data, execution_date=20220607T092447, start_date=20220607T092451, end_date=20220607T092451
[2022-06-07 09:24:51,555] {standard_task_runner.py:97} ERROR - Failed to execute job 86 for task copy_restaurant_detail_data (duplicate key value violates unique constraint "restaurant_detail_pkey"
DETAIL:  Key (id)=(R_99988) already exists.
CONTEXT:  COPY restaurant_detail, line 2
; 18102)
[2022-06-07 09:24:51,578] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-07 09:24:51,668] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
