[2022-06-08 02:40:04,980] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: hands_on_test.postgreq_data_quality_check scheduled__2022-06-07T00:00:00+00:00 [queued]>
[2022-06-08 02:40:04,997] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: hands_on_test.postgreq_data_quality_check scheduled__2022-06-07T00:00:00+00:00 [queued]>
[2022-06-08 02:40:04,999] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-08 02:40:05,004] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-06-08 02:40:05,005] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-08 02:40:05,027] {taskinstance.py:1377} INFO - Executing <Task(PostgresDataQualityOperator): postgreq_data_quality_check> on 2022-06-07 00:00:00+00:00
[2022-06-08 02:40:05,033] {standard_task_runner.py:52} INFO - Started process 322 to run task
[2022-06-08 02:40:05,039] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'hands_on_test', 'postgreq_data_quality_check', 'scheduled__2022-06-07T00:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpn1qw_6hx', '--error-file', '/tmp/tmp9ghmpdxe']
[2022-06-08 02:40:05,042] {standard_task_runner.py:80} INFO - Job 12: Subtask postgreq_data_quality_check
[2022-06-08 02:40:05,150] {task_command.py:369} INFO - Running <TaskInstance: hands_on_test.postgreq_data_quality_check scheduled__2022-06-07T00:00:00+00:00 [running]> on host b79bd65fcc57
[2022-06-08 02:40:05,269] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=pathairs
AIRFLOW_CTX_DAG_ID=hands_on_test
AIRFLOW_CTX_TASK_ID=postgreq_data_quality_check
AIRFLOW_CTX_EXECUTION_DATE=2022-06-07T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-07T00:00:00+00:00
[2022-06-08 02:40:05,272] {data_quality.py:20} INFO - DataQualityOperator
[2022-06-08 02:40:05,290] {base.py:68} INFO - Using connection ID 'postgres_db' for task execution.
[2022-06-08 02:40:05,320] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/plugins/operators/data_quality.py", line 26, in execute
    result = postgres.get_records(sql)[0][0]
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 144, in get_records
    cur.execute(sql)
psycopg2.errors.UndefinedTable: relation "order_detail" does not exist
LINE 1: SELECT COUNT(*) FROM order_detail;
                             ^

[2022-06-08 02:40:05,402] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=hands_on_test, task_id=postgreq_data_quality_check, execution_date=20220607T000000, start_date=20220608T024004, end_date=20220608T024005
[2022-06-08 02:40:05,431] {standard_task_runner.py:97} ERROR - Failed to execute job 12 for task postgreq_data_quality_check (relation "order_detail" does not exist
LINE 1: SELECT COUNT(*) FROM order_detail;
                             ^
; 322)
[2022-06-08 02:40:05,455] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-08 02:40:05,548] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-06-08 05:17:07,952] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: hands_on_test.postgreq_data_quality_check scheduled__2022-06-07T00:00:00+00:00 [queued]>
[2022-06-08 05:17:07,976] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: hands_on_test.postgreq_data_quality_check scheduled__2022-06-07T00:00:00+00:00 [queued]>
[2022-06-08 05:17:07,977] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-08 05:17:07,978] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-06-08 05:17:07,979] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-08 05:17:08,003] {taskinstance.py:1377} INFO - Executing <Task(PostgresDataQualityOperator): postgreq_data_quality_check> on 2022-06-07 00:00:00+00:00
[2022-06-08 05:17:08,010] {standard_task_runner.py:52} INFO - Started process 11013 to run task
[2022-06-08 05:17:08,015] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'hands_on_test', 'postgreq_data_quality_check', 'scheduled__2022-06-07T00:00:00+00:00', '--job-id', '149', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpw5rv434c', '--error-file', '/tmp/tmp7ex_nvcr']
[2022-06-08 05:17:08,017] {standard_task_runner.py:80} INFO - Job 149: Subtask postgreq_data_quality_check
[2022-06-08 05:17:08,094] {task_command.py:369} INFO - Running <TaskInstance: hands_on_test.postgreq_data_quality_check scheduled__2022-06-07T00:00:00+00:00 [running]> on host b79bd65fcc57
[2022-06-08 05:17:08,193] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=hands_on_test
AIRFLOW_CTX_TASK_ID=postgreq_data_quality_check
AIRFLOW_CTX_EXECUTION_DATE=2022-06-07T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-07T00:00:00+00:00
[2022-06-08 05:17:08,195] {data_quality.py:20} INFO - DataQualityOperator
[2022-06-08 05:17:08,209] {base.py:68} INFO - Using connection ID 'postgres_db' for task execution.
[2022-06-08 05:17:08,282] {base.py:68} INFO - Using connection ID 'postgres_db' for task execution.
[2022-06-08 05:17:08,300] {data_quality.py:36} WARNING - Data quality check passed
[2022-06-08 05:17:08,317] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=hands_on_test, task_id=postgreq_data_quality_check, execution_date=20220607T000000, start_date=20220608T051707, end_date=20220608T051708
[2022-06-08 05:17:08,349] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-08 05:17:08,421] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
