[2022-06-07 06:17:28,178] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: hands_on_test.create_hive_order_detail scheduled__2022-06-06T00:00:00+00:00 [queued]>
[2022-06-07 06:17:28,218] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: hands_on_test.create_hive_order_detail scheduled__2022-06-06T00:00:00+00:00 [queued]>
[2022-06-07 06:17:28,219] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-07 06:17:28,220] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-06-07 06:17:28,221] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-07 06:17:28,252] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): create_hive_order_detail> on 2022-06-06 00:00:00+00:00
[2022-06-07 06:17:28,281] {standard_task_runner.py:52} INFO - Started process 6478 to run task
[2022-06-07 06:17:28,308] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'hands_on_test', 'create_hive_order_detail', 'scheduled__2022-06-06T00:00:00+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpdcbhmm_v', '--error-file', '/tmp/tmpj1li897v']
[2022-06-07 06:17:28,313] {standard_task_runner.py:80} INFO - Job 47: Subtask create_hive_order_detail
[2022-06-07 06:17:28,474] {task_command.py:369} INFO - Running <TaskInstance: hands_on_test.create_hive_order_detail scheduled__2022-06-06T00:00:00+00:00 [running]> on host a4a1e1d603db
[2022-06-07 06:17:28,785] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=pathairs
AIRFLOW_CTX_DAG_ID=hands_on_test
AIRFLOW_CTX_TASK_ID=create_hive_order_detail
AIRFLOW_CTX_EXECUTION_DATE=2022-06-06T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-06T00:00:00+00:00
[2022-06-07 06:17:28,789] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-06-07 06:17:28,792] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'docker exec hive-server hive -f /opt/hql/order_detail.hql ']
[2022-06-07 06:17:28,821] {subprocess.py:85} INFO - Output:
[2022-06-07 06:17:34,442] {subprocess.py:92} INFO - SLF4J: Class path contains multiple SLF4J bindings.
[2022-06-07 06:17:34,444] {subprocess.py:92} INFO - SLF4J: Found binding in [jar:file:/opt/hive/lib/log4j-slf4j-impl-2.6.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
[2022-06-07 06:17:34,445] {subprocess.py:92} INFO - SLF4J: Found binding in [jar:file:/opt/hadoop-2.7.4/share/hadoop/common/lib/slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
[2022-06-07 06:17:34,446] {subprocess.py:92} INFO - SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
[2022-06-07 06:17:34,447] {subprocess.py:92} INFO - SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
[2022-06-07 06:17:37,222] {subprocess.py:92} INFO - 
[2022-06-07 06:17:37,223] {subprocess.py:92} INFO - Logging initialized using configuration in file:/opt/hive/conf/hive-log4j2.properties Async: true
[2022-06-07 06:17:39,957] {subprocess.py:92} INFO - Could not open input file for reading. (File file:/opt/hql/order_detail.hql does not exist)
[2022-06-07 06:17:43,454] {subprocess.py:96} INFO - Command exited with return code 3
[2022-06-07 06:17:43,477] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 3.
[2022-06-07 06:17:43,483] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=hands_on_test, task_id=create_hive_order_detail, execution_date=20220606T000000, start_date=20220607T061728, end_date=20220607T061743
[2022-06-07 06:17:43,504] {standard_task_runner.py:97} ERROR - Failed to execute job 47 for task create_hive_order_detail (Bash command failed. The command returned a non-zero exit code 3.; 6478)
[2022-06-07 06:17:43,523] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-07 06:17:43,588] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
