[2022-06-06 11:32:59,364] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: hands_on_test.copy_order_detail_data manual__2022-06-06T11:06:44.654504+00:00 [queued]>
[2022-06-06 11:32:59,380] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: hands_on_test.copy_order_detail_data manual__2022-06-06T11:06:44.654504+00:00 [queued]>
[2022-06-06 11:32:59,381] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-06 11:32:59,381] {taskinstance.py:1357} INFO - Starting attempt 2 of 2
[2022-06-06 11:32:59,382] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-06 11:32:59,402] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): copy_order_detail_data> on 2022-06-06 11:06:44.654504+00:00
[2022-06-06 11:32:59,408] {standard_task_runner.py:52} INFO - Started process 2339 to run task
[2022-06-06 11:32:59,414] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'hands_on_test', 'copy_order_detail_data', 'manual__2022-06-06T11:06:44.654504+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpc4cbbklz', '--error-file', '/tmp/tmprw_8d4r3']
[2022-06-06 11:32:59,416] {standard_task_runner.py:80} INFO - Job 21: Subtask copy_order_detail_data
[2022-06-06 11:32:59,495] {task_command.py:369} INFO - Running <TaskInstance: hands_on_test.copy_order_detail_data manual__2022-06-06T11:06:44.654504+00:00 [running]> on host 0c241499c9fe
[2022-06-06 11:32:59,597] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=pathairs
AIRFLOW_CTX_DAG_ID=hands_on_test
AIRFLOW_CTX_TASK_ID=copy_order_detail_data
AIRFLOW_CTX_EXECUTION_DATE=2022-06-06T11:06:44.654504+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-06T11:06:44.654504+00:00
[2022-06-06 11:32:59,612] {base.py:68} INFO - Using connection ID 'postgres_db' for task execution.
[2022-06-06 11:32:59,628] {dbapi.py:208} INFO - Running statement: 
COPY order_detail FROM '/var/lib/postgresql/data/lmwn/order_detail.csv' DELIMITER ',' CSV HEADER;, parameters: None
[2022-06-06 11:32:59,632] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 92, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 188, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 212, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedFile: could not open file "/var/lib/postgresql/data/lmwn/order_detail.csv" for reading: No such file or directory
HINT:  COPY FROM instructs the PostgreSQL server process to read a file. You may want a client-side facility such as psql's \copy.

[2022-06-06 11:32:59,647] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=hands_on_test, task_id=copy_order_detail_data, execution_date=20220606T110644, start_date=20220606T113259, end_date=20220606T113259
[2022-06-06 11:32:59,662] {standard_task_runner.py:97} ERROR - Failed to execute job 21 for task copy_order_detail_data (could not open file "/var/lib/postgresql/data/lmwn/order_detail.csv" for reading: No such file or directory
HINT:  COPY FROM instructs the PostgreSQL server process to read a file. You may want a client-side facility such as psql's \copy.
; 2339)
[2022-06-06 11:32:59,707] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-06 11:32:59,771] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
