[2022-06-06 11:43:04,758] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: hands_on_test.copy_restaurant_detail_data scheduled__2022-06-05T00:00:00+00:00 [queued]>
[2022-06-06 11:43:04,800] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: hands_on_test.copy_restaurant_detail_data scheduled__2022-06-05T00:00:00+00:00 [queued]>
[2022-06-06 11:43:04,801] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-06 11:43:04,802] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-06-06 11:43:04,803] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-06 11:43:04,848] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): copy_restaurant_detail_data> on 2022-06-05 00:00:00+00:00
[2022-06-06 11:43:04,858] {standard_task_runner.py:52} INFO - Started process 3162 to run task
[2022-06-06 11:43:04,876] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'hands_on_test', 'copy_restaurant_detail_data', 'scheduled__2022-06-05T00:00:00+00:00', '--job-id', '56', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpgmz7afmq', '--error-file', '/tmp/tmp1ojk_71s']
[2022-06-06 11:43:04,884] {standard_task_runner.py:80} INFO - Job 56: Subtask copy_restaurant_detail_data
[2022-06-06 11:43:05,022] {task_command.py:369} INFO - Running <TaskInstance: hands_on_test.copy_restaurant_detail_data scheduled__2022-06-05T00:00:00+00:00 [running]> on host 0c241499c9fe
[2022-06-06 11:43:05,200] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=pathairs
AIRFLOW_CTX_DAG_ID=hands_on_test
AIRFLOW_CTX_TASK_ID=copy_restaurant_detail_data
AIRFLOW_CTX_EXECUTION_DATE=2022-06-05T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-05T00:00:00+00:00
[2022-06-06 11:43:05,220] {base.py:68} INFO - Using connection ID 'postgres_db' for task execution.
[2022-06-06 11:43:05,238] {dbapi.py:208} INFO - Running statement: 
COPY restaurant_detail FROM '/var/lib/postgresql/data/restaurant_detail.csv' DELIMITER ',' CSV HEADER;, parameters: None
[2022-06-06 11:43:05,244] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 92, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 188, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 212, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedTable: relation "restaurant_detail" does not exist

[2022-06-06 11:43:05,271] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=hands_on_test, task_id=copy_restaurant_detail_data, execution_date=20220605T000000, start_date=20220606T114304, end_date=20220606T114305
[2022-06-06 11:43:05,325] {standard_task_runner.py:97} ERROR - Failed to execute job 56 for task copy_restaurant_detail_data (relation "restaurant_detail" does not exist
; 3162)
[2022-06-06 11:43:05,364] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-06 11:43:05,523] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
